### PR TITLE
changing to cookie cutter templating

### LINKED ISSUE #1: Cookie-cutter templating.
The current state for this uses the generate_template.py script as a one-off. This is requires a few more system calls, nuking the .git folder, and calling this repository separately each time.

### PR DESCRIPTION
**Pull request by itsbenweeks**
This will resolve #1, #2, and #5.

### CODE REVIEW

**Comment by pdpinch** [comment]
Hey Ben, do you need a review on this, or do you want to just merge it?

**Comment by pdpinch** [comment]
@itsbenweeks Just checking in on this again. Do you need a review?

**Comment by itsbenweeks** [comment]
Sorry for missing your reply last week, @pdpinch. After having not touched this in 4 months, I've lost some contex on this. Let me reorient myself to thist, and I'll let you know.

**Comment by itsbenweeks** [comment]
I think I'll scrap this. At the time, using one template for studio and latex2edx made sense. Having conditionally generated files causes cookie-cutter to raise an exception. Granted, that exception is raised after all the necessary files are generated, so it functionally works, but it's poor practice. Having separate branches for studio, latex2edx, and xml courses would make a bit more sense. 

It may be best to keep it as minimal as possible, as well. The fellows course can be a place to see 'best practices' in action. Giving all of that to a new course creator can be a little overwhelming for them.

**Pull request closed without merging**
